### ISSUE TITLE
console.log in server components not showing up 

### ISSUE THREAD

**Issue by AlexDaichendt** [cloudflare/next-on-pages#24] opened 2022-11-17 19:26 UTC
Hey,

Apparently, when I add `console.log`s in a server component (to find out how next-on-pages behaves) the output never shows up in neither next-on-pages nor pages. 

I run following commands for the dev environment in seperate shells: 
```
npx @cloudflare/next-on-pages --watch
npx wrangler pages dev .vercel/output/static --compatibility-flags=streams_enable_constructors
```

I don't know exactly how RSC' work, or if I am reporting this in the right location, but regardless, I think it is expected behaviour to get the outputs somewhere. When I run `next dev` I get the outputs. 

Thanks!

**Comment by dario-piotrowicz** [comment] 2023-03-30 15:57
Seems like it's working as expected for me, in a RSC component you get the console.log message in the terminal running wrangler pages:
![Screenshot 2023-03-30 at 16 55 05](https://user-images.githubusercontent.com/61631103/228894554-9bc5b794-4605-4249-a904-344a07953b88.png)

@AlexDaichendt could you try again and let us know if it is still an issue? (maybe it got fixed by either our changes on Next's since you opened the issue?)

**Comment by dario-piotrowicz** [comment] 2023-03-30 15:58
If it doesn't work could you please provide some code or a minimal reproduction so that we can investigate further?

**Comment by dario-piotrowicz** [comment] 2023-04-19 10:29
I'm closing the issue as I haven't yet received a reply to the above comment and suspect that this is no longer an issue

@AlexDaichendt if you circle back to this and still have issues with it please feel free to reopen the issue and/or ping me

**Closed by dario-piotrowicz** 2023-04-19 10:29 UTC
Labels: question
