### ISSUE TITLE
Guidance for reading KV (etc) bindings locally

### ISSUE THREAD

**Issue by timfee** [cloudflare/next-on-pages#321] opened 2023-06-21 15:58 UTC
### Description

Hi there,

I noticed that the docs advise running build (watch) + serve for local development, but I wasn’t sure if this pattern was suitable for HMR-enabled fast, `next dev`-esque development locally. 

In particular, I was looking to get the values from KV passed into the instance with low overhead. 

### Additional Information

I was considering a monorepo pattern but it seemed like a lot of headache / overkill - so wanted to see if I was missing something obvious or if folks have approached this in other ways :)

### Would you like to help?

- [ ] Would you like to help implement this feature?

**Comment by james-elicx** [comment] 2023-06-21 20:10
Hey there, thanks for bringing this up. It's actually an area that we are actively exploring and looking at.

At the moment, the only way to access bindings is through our watch mode. Sadly, this means that we have to do a full build of the application and it loses out on the fast HMR that `next dev` has 🙁.

One of the alternatives that we're exploring is an experimental proxy that would enable access to bindings during local development. However, there are conflicting opinions within the team at Cloudflare on how best to proceed, so it's currently on hold.

There is another issue (https://github.com/cloudflare/next-on-pages/issues/271) open where we are tracking this feature request. I kindly ask that you consider sharing more information about your use case, the problems you are currently facing, and how you would prefer interacting with bindings in `next dev`, over in that thread.

**Comment by dario-piotrowicz** [comment] 2023-06-21 21:04
Thanks a lot for the issue @timfee 🙂

As James said this is unfortunately an existing pain point which we most definitely need to address 😓, I'm sorry about it, I hope we can make the situation better soon

I'm closing the issue as it is a duplicate of #271 and it's better to keep all conversation centralized there, I hope you don't mind 🙂

**Closed by dario-piotrowicz** 2023-06-21 21:04 UTC
Labels: enhancement

**Comment by tom-huntington** [comment] 2023-06-21 21:56
I might add that all of the vite frameworks (svelte, solid, remix, ect) do HMR with the cloudflare bindings

**Comment by rohanrehman** [comment] 2024-08-07 09:03
This should be revisited as KV bindings are not working when running localy.
