### ISSUE TITLE
[🐛 Bug]: build failed when using clerk

### ISSUE THREAD

**Issue by antscript** [cloudflare/next-on-pages#483] opened 2023-10-05 08:58 UTC
### next-on-pages environment related information

System:
	Platform: darwin
	Arch: arm64
	Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
	CPU: (10) arm64 Apple M1 Pro
	Memory: 32 GB
	Shell: /bin/zsh
Binaries:
	Node: 16.16.0
	Bun: N/A
	pnpm: 8.8.0
	Yarn: 1.22.19
	npm: 8.11.0
Package Manager Used: npm
Relevant Packages:
	@cloudflare/next-on-pages: 1.6.3
	vercel: 32.4.1
	next: 13.5.4

### Description

build failed when using [clerk](https://clerk.com), I made a demo: [github link](https://github.com/antscript/nextjs-on-cloudflare-pages).

> ⚡️ Warning: your app/not-found route might contain runtime logic, this is currently
> ⚡️ not supported by @cloudflare/next-on-pages, if that's actually the case please
> ⚡️ remove the runtime logic from your not-found route
> 
> ⚡️ ERROR: Failed to produce a Cloudflare Pages build from the project.
> ⚡️
> ⚡️ 	The following routes were not configured to run with the Edge Runtime:
> ⚡️ 	  - /_error
> ⚡️ 	  - /_not-found
> ⚡️ 	  - /about
> ⚡️ 	  - /index
> ⚡️
> ⚡️ 	Please make sure that all your non-static routes export the following edge runtime route segment config:
> ⚡️ 	  export const runtime = 'edge';
> ⚡️
> ⚡️ 	You can read more about the Edge Runtime on the Next.js documentation:
> ⚡️ 	  https://nextjs.org/docs/app/building-your-application/rendering/edge-and-nodejs-runtimes

### Reproduction

1. `npm create cloudflare@latest my-next-app -- --framework=next`
2. `npm run pages:build` -> Success
3. add src/app/about/page.tsx
4. `npm run pages:build` -> Success
5. `npm install @clerk/nextjs`
6. setup clerk( [https://clerk.com/docs/quickstarts/nextjs](https://clerk.com/docs/quickstarts/nextjs) )
7. `npm run pages:build` -> Failed

error message:

> nextjs-on-cloudflare-pages@0.1.0 pages:build
> npx @cloudflare/next-on-pages@1
> 
> ⚡️ @cloudflare/next-on-pages CLI v.1.6.3
> ⚡️ Detected Package Manager: npm
> ⚡️ Preparing project...
> ⚡️ Project is ready
> ⚡️ Building project...
> ▲  Vercel CLI 32.4.1
> ▲  WARNING: You should not upload the `.next` directory.
> ▲  Installing dependencies...
> ▲  up to date in 371ms
> ▲  131 packages are looking for funding
> ▲  run `npm fund` for details
> ▲  Detected Next.js version: 13.5.4
> ▲  Detected `package-lock.json` generated by npm 7+
> ▲  Running "npm run build"
> ▲  > nextjs-on-cloudflare-pages@0.1.0 build
> ▲  > next build
> ▲  Creating an optimized production build ...
> ▲  ⚠ Compiled with warnings
> ▲  ./node_modules/@clerk/shared/dist/esm/utils/localStorageBroadcastChannel.js
> ▲  A Node.js API is used (MessageEvent at line: 26) which is not supported in the Edge Runtime.
> ▲  Learn more: https://nextjs.org/docs/api-reference/edge-runtime
> ▲
> ▲  Import trace for requested module:
> ▲  ./node_modules/@clerk/shared/dist/esm/utils/localStorageBroadcastChannel.js
> ▲  ./node_modules/@clerk/shared/dist/esm/utils/index.js
> ▲  ./node_modules/@clerk/shared/dist/esm/index.js
> ▲  ./node_modules/@clerk/nextjs/dist/esm/server/withClerkMiddleware.js
> ▲  ./node_modules/@clerk/nextjs/dist/esm/server-helpers.server.js
> ▲  ./node_modules/@clerk/nextjs/dist/esm/index.js
> ▲
> ▲  ./node_modules/scheduler/cjs/scheduler.production.min.js
> ▲  A Node.js API is used (setImmediate at line: 51) which is not supported in the Edge Runtime.
> ▲  Learn more: https://nextjs.org/docs/api-reference/edge-runtime
> ▲
> ▲  Import trace for requested module:
> ▲  ./node_modules/scheduler/cjs/scheduler.production.min.js
> ▲  ./node_modules/scheduler/index.js
> ▲  ./node_modules/react-dom/cjs/react-dom.production.min.js
> ▲  ./node_modules/react-dom/index.js
> ▲  ./node_modules/next/dist/esm/client/script.js
> ▲  ./node_modules/next/dist/esm/shared/lib/router/router.js
> ▲  ./node_modules/next/dist/esm/client/router.js
> ▲  ./node_modules/next/router.js
> ▲  ./node_modules/@clerk/nextjs/dist/esm/pages/ClerkProvider.js
> ▲  ./node_modules/@clerk/nextjs/dist/esm/components.client.js
> ▲  ./node_modules/@clerk/nextjs/dist/esm/index.js
> ▲
> ▲  ./node_modules/scheduler/cjs/scheduler.production.min.js
> ▲  A Node.js API is used (setImmediate at line: 51) which is not supported in the Edge Runtime.
> ▲  Learn more: https://nextjs.org/docs/api-reference/edge-runtime
> ▲
> ▲  Import trace for requested module:
> ▲  ./node_modules/scheduler/cjs/scheduler.production.min.js
> ▲  ./node_modules/scheduler/index.js
> ▲  ./node_modules/react-dom/cjs/react-dom.production.min.js
> ▲  ./node_modules/react-dom/index.js
> ▲  ./node_modules/next/dist/esm/client/script.js
> ▲  ./node_modules/next/dist/esm/shared/lib/router/router.js
> ▲  ./node_modules/next/dist/esm/client/router.js
> ▲  ./node_modules/next/router.js
> ▲  ./node_modules/@clerk/nextjs/dist/esm/pages/ClerkProvider.js
> ▲  ./node_modules/@clerk/nextjs/dist/esm/components.client.js
> ▲  ./node_modules/@clerk/nextjs/dist/esm/index.js
> ▲
> ▲  ./node_modules/scheduler/cjs/scheduler.production.min.js
> ▲  A Node.js API is used (MessageChannel at line: 120) which is not supported in the Edge Runtime.
> ▲  Learn more: https://nextjs.org/docs/api-reference/edge-runtime
> ▲
> ▲  Import trace for requested module:
> ▲  ./node_modules/scheduler/cjs/scheduler.production.min.js
> ▲  ./node_modules/scheduler/index.js
> ▲  ./node_modules/react-dom/cjs/react-dom.production.min.js
> ▲  ./node_modules/react-dom/index.js
> ▲  ./node_modules/next/dist/esm/client/script.js
> ▲  ./node_modules/next/dist/esm/shared/lib/router/router.js
> ▲  ./node_modules/next/dist/esm/client/router.js
> ▲  ./node_modules/next/router.js
> ▲  ./node_modules/@clerk/nextjs/dist/esm/pages/ClerkProvider.js
> ▲  ./node_modules/@clerk/nextjs/dist/esm/components.client.js
> ▲  ./node_modules/@clerk/nextjs/dist/esm/index.js
> ▲
> ▲  ./node_modules/scheduler/cjs/scheduler.production.min.js
> ▲  A Node.js API is used (MessageChannel at line: 121) which is not supported in the Edge Runtime.
> ▲  Learn more: https://nextjs.org/docs/api-reference/edge-runtime
> ▲
> ▲  Import trace for requested module:
> ▲  ./node_modules/scheduler/cjs/scheduler.production.min.js
> ▲  ./node_modules/scheduler/index.js
> ▲  ./node_modules/react-dom/cjs/react-dom.production.min.js
> ▲  ./node_modules/react-dom/index.js
> ▲  ./node_modules/next/dist/esm/client/script.js
> ▲  ./node_modules/next/dist/esm/shared/lib/router/router.js
> ▲  ./node_modules/next/dist/esm/client/router.js
> ▲  ./node_modules/next/router.js
> ▲  ./node_modules/@clerk/nextjs/dist/esm/pages/ClerkProvider.js
> ▲  ./node_modules/@clerk/nextjs/dist/esm/components.client.js
> ▲  ./node_modules/@clerk/nextjs/dist/esm/index.js
> ▲  Linting and checking validity of types ...
> ▲  Collecting page data ...
> ▲  ⚠ Using edge runtime on a page currently disables static generation for that page
> ▲  Generating static pages (0/6) ...
> ▲  (node:45866) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
> ▲  (Use `node --trace-warnings ...` to show where the warning was created)
> ▲  Generating static pages (1/6)
> ▲  Generating static pages (2/6)
> ▲  Generating static pages (4/6)
> ▲  ✓ Generating static pages (6/6)
> ▲  Finalizing page optimization ...
> ▲  Collecting build traces ...
> ▲
> ▲  Route (app)                              Size     First Load JS
> ▲  ┌ λ /                                    5.25 kB        85.7 kB
> ▲  ├ λ /_not-found                          883 B          81.3 kB
> ▲  ├ λ /about                               137 B          80.6 kB
> ▲  └ ℇ /api/hello                           0 B                0 B
> ▲  + First Load JS shared by all            80.4 kB
> ▲  ├ chunks/864-79096e19314fbce2.js       27.5 kB
> ▲  ├ chunks/fd9d1056-8779eae5e0c68f1d.js  51 kB
> ▲  ├ chunks/main-app-d39fd87bd3371f02.js  234 B
> ▲  └ chunks/webpack-c7cde591d063263b.js   1.75 kB
> ▲
> ▲
> ▲  ƒ Middleware                             188 kB
> ▲  ℇ  (Streaming)  server-side renders with streaming (uses React 18 SSR streaming or Server Components)
> ▲  λ  (Server)     server-side renders at runtime (uses getInitialProps or getServerSideProps)
> ▲  Traced Next.js server files in: 496.122ms
> ▲  Created all serverless functions in: 1.194s
> ▲  Collected static files (public/, static/, .next/static): 2.874ms
> ▲  Build Completed in .vercel/output [14s]
> ⚡️ Completed `npx vercel build`.
> ⚡️ Warning: your app/not-found route might contain runtime logic, this is currently
> ⚡️ not supported by @cloudflare/next-on-pages, if that's actually the case please
> ⚡️ remove the runtime logic from your not-found route
> 
> ⚡️ ERROR: Failed to produce a Cloudflare Pages build from the project.
> ⚡️
> ⚡️ 	The following routes were not configured to run with the Edge Runtime:
> ⚡️ 	  - /_error
> ⚡️ 	  - /_not-found
> ⚡️ 	  - /about
> ⚡️ 	  - /index
> ⚡️
> ⚡️ 	Please make sure that all your non-static routes export the following edge runtime route segment config:
> ⚡️ 	  export const runtime = 'edge';
> ⚡️
> ⚡️ 	You can read more about the Edge Runtime on the Next.js documentation:
> ⚡️ 	  https://nextjs.org/docs/app/building-your-application/rendering/edge-and-nodejs-runtimes

### Pages Deployment Method

Direct Upload (`wrangler pages publish` or the @cloudflare/pages-action GitHub Action)

### Would you like to help?

- [x] Would you like to help fixing this bug?

**Comment by brianfryer** [comment] 2023-10-06 12:23
Maybe related to https://github.com/cloudflare/next-on-pages/issues/413 🤞

**Comment by antscript** [comment] 2023-10-07 06:30
> Maybe related to #413 🤞

Thanks for the information you shared. After trying various methods, I still can’t completely solve this problem. Therefore, I decided to separate the server and the web page, and no longer use full-stack projects to avoid this problem. Thanks again.

**Comment by dario-piotrowicz** [comment] 2023-12-17 20:50
Hi @antscript, thanks for the issue 🙂 

so sorry for the late reply 😓 🙇 

I've investigated this and the problem was partially caused by #413 which has been resolved

Besides that there's an additional bug that I've discovered that is causing this issue with the clerk package: https://github.com/cloudflare/next-on-pages/issues/598

I will look into the issue in the next few days, once that's solved that should also fix this issue, I will keep you posted 🙂 
(hoping that it won't be too late for you since you've separated the server and client side of your app 😓)

**Comment by antscript** [comment] 2023-12-18 07:32
> Hi @antscript, thanks for the issue 🙂
> 
> so sorry for the late reply 😓 🙇
> 
> I've investigated this and the problem was partially caused by #413 which has been resolved我对此进行了调查，问题部分是由 #413 引起的，该问题已得到解决
> 
> Besides that there's an additional bug that I've discovered that is causing this issue with the clerk package: #598除此之外，我还发现了一个导致 clerk 包出现此问题的额外错误：#598
> 
> I will look into the issue in the next few days, once that's solved that should also fix this issue, I will keep you posted 🙂我将在接下来的几天内调查这个问题，一旦解决了，也应该解决这个问题，我会随时通知您🙂 (hoping that it won't be too late for you since you've separated the server and client side of your app 😓)（希望对您来说不会太晚，因为您已经将应用程序的服务器端和客户端分开了😓）


Thanks for your reply! 

I hope you can solve this problem smoothly, and my future projects will no longer separate the server and client. 

Thanks again!

**Comment by dario-piotrowicz** [comment] 2023-12-18 15:56
@antscript I've checked the issue and I think that it can't be fixed by next-on-pages, but I think that it can be easily solved by creating a `not-found` route that uses the `edge` runtime (as you can see in my [minimal reproduction](https://github.com/dario-piotrowicz/next-on-pages-issue-598-reproduction/pull/1)).

So I am simply expanding our documentation to specify that ([here](https://github.com/cloudflare/next-on-pages/blob/56391355c3028737a4b0069a5126ccaec24e53b1/packages/next-on-pages/docs/gotchas.md#not-found)).

So in your case I do believe that you can solve the issue with clerk by:
 - using the [latest beta next-on-pages release](https://www.npmjs.com/package/@cloudflare/next-on-pages/v/0.0.0-352bf4b) (which includes the #413 fix)
 - and creating a not-found route that is either static or uses the `edge` runtime
 
 Can you double check that and let me know if it fixes your issue? 🙏

**Comment by dario-piotrowicz** [comment] 2024-02-19 22:24
Closing the issue due to a lack of response from my previous message

@antscript I hope it's fine by you, if you go back to this please feel free to reopen the issue if needed 🙏

**Closed by dario-piotrowicz** 2024-02-19 22:24 UTC
Labels: bug, question
