### ISSUE TITLE
[🐛 Bug]: missing types in v1.13.0

### ISSUE THREAD

**Issue by aryasaatvik** [cloudflare/next-on-pages#841] opened 2024-07-30 05:12 UTC
### Description

types are not bundled with the package starting at v1.13.0 https://npmjs.com/package/@cloudflare/next-on-pages/v/1.13.0?activeTab=code

v1.12.1 looks like the last version to contain types
https://www.npmjs.com/package/@cloudflare/next-on-pages/v/1.12.1?activeTab=code

### Pages Deployment Method

None

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment] 2024-07-30 17:21
Hey @aryasaatvik (and @ItsWendell), thanks for the issue, this is a duplicate of https://github.com/cloudflare/next-on-pages/issues/840

Anyways I've just made a new release that fixes the issue, please try again with `v1.13.1` (and let me know if it doesn't work for you) 🙏 

Sorry for the inconvenience 🙇

**Closed by dario-piotrowicz** 2024-07-30 17:21 UTC
Labels: bug
