### ISSUE TITLE
Fail to pass env to Pages Functions

### ISSUE THREAD

**Issue by shiyuhang0** [cloudflare/next-on-pages#53] opened 2023-01-11 10:46 UTC
The @cloudflare/next-on-pages CLI transforms the Edge Runtime components of your project into a _worker.js file which is deployed with [Pages Functions](https://developers.cloudflare.com/pages/platform/functions/#advanced-mode)

When I deploy a Cloudflare page with Prisma data proxy, I set the `DATABASE_URL` in page settings like this 

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/52435083/211786292-9ef6ec9d-4784-44b8-9d73-ae1695f9735a.png">

But I find the deployment fails:

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/52435083/211786468-1b1b4b0b-f94f-43b7-8799-2f7bbf289ee7.png">

I think it may be because next-on-pages CLI fails to pass the env from page to Pages Functions.  How Can I solve this issue? thanks

**Comment by GregBrimble** [comment] 2023-01-11 11:52
Closed as duplicate of #1

**Closed by GregBrimble** 2023-01-11 11:52 UTC

**Comment by shiyuhang0** [comment] 2023-01-11 12:22
I look through issue 1 but did't find a good solution. is there a workaround?
