### ISSUE TITLE
Next.js 13.2 dependency causes "Internal Server Error" on site render, `nodejs_compat` workaround is not permitted

### ISSUE THREAD

**Issue by AaronFriel** [cloudflare/next-on-pages#79] opened 2023-02-27 00:53 UTC
As described in #76, AsyncLocalStorage causes Nextjs 13.2 to fail to run if a 13.1 template is used. This is caused by creating a site with:

```sh
npx create-next-app@~13.1
```

And noting that the version of Next selected in package.json may be 13.2 or newer.

The workaround mentioned in #76 does not work:

> 16:46:07.894	Error: Failed to publish your Function. Got error: The compatibility flag nodejs_compat is experimental and cannot yet be used in Workers deployed to Cloudflare.

**Comment by GregBrimble** [comment] 2023-03-01 16:17
Closed as dupe of #76

**Closed by GregBrimble** 2023-03-01 16:17 UTC
