### ISSUE TITLE
Next.js 13.2 template causes build error "Could not map all functions to an entry in the manifest."

### ISSUE THREAD

**Issue by AaronFriel** [cloudflare/next-on-pages#78] opened 2023-02-27 00:48 UTC
Starting from Next.js 13.2.x (`@latest` as I write this), the site will fail to build with an error. This is caused by creating a site with:

```
npx create-next-app@~13.2
```

Error:

```
16:08:11.591	⚡️
16:08:11.592	⚡️
16:08:11.592	⚡️ Completed 'npx vercel build'.
16:08:11.593	⚡️
16:08:12.393	⚡️ ERROR: Could not map all functions to an entry in the manifest.
16:08:12.394	⚡️ Please report this at https://github.com/cloudflare/next-on-pages/issues.
```

**Comment by gvatsov** [comment] 2023-02-28 15:57
You could check if it is the same reason and resolution as [this one](https://github.com/cloudflare/next-on-pages/issues/42). Cheers!

**Comment by mataspetrikas** [comment] 2023-03-10 15:29
also getting the same error, on a basic config:

```
const nextConfig = {
  experimental: {
    appDir: true,
    runtime: 'experimental-edge',
  },
};
```

**Comment by n00el** [comment] 2023-03-16 06:51
> You could check if it is the same reason and resolution as [this one](https://github.com/cloudflare/next-on-pages/issues/42). Cheers!

Can we forgot this one ticket already? Users getting the same error withouth using the basePath...

**Comment by gvatsov** [comment] 2023-03-16 08:14
> also getting the same error, on a basic config:
> 
> ```
> const nextConfig = {
>   experimental: {
>     appDir: true,
>     runtime: 'experimental-edge',
>   },
> };
> ```

Are you getting the error on Windows machine?

**Comment by zizifn** [comment] 2023-03-16 18:19
My case is this error is in pages build CI, I would say this is 100% reproduce if enable nextjs appDir: true with version 13.2

**Comment by dario-piotrowicz** [comment] 2023-04-05 11:00
@AaronFriel we've made improvements since you've opened the issue and I've deployed various apps using the app dir with 13.2.x, like this one for example: https://simple-pages-dir-1324.pages.dev/

So I think yours is no longer an issue, could you please double check and let me know if you still have any problems with app dir applications using the latest next-on-pages? (PS: remember to set the nodejs_compat flag which is necessary for such apps to run on Pages)

**Comment by dario-piotrowicz** [comment] 2023-04-25 10:46
I'm closing the issue as I haven't yet received a reply to the above comment and suspect that this is no longer an issue

@AaronFriel if you still have some issue with app dir with Next.js 13.2  please feel free to reopen the issue and/or ping me

as well as @mataspetrikas, @gvatsov and @zizifn I hope things are working for you now, if they are not please ping me or open a new issue 🙏

**Closed by dario-piotrowicz** 2023-04-25 10:46 UTC
Labels: question
