### ISSUE TITLE
[🐛 Bug]: Command does not work with monorepos x yarn berry

### ISSUE THREAD

**Issue by 1337LutZ** [cloudflare/next-on-pages#467] opened 2023-09-20 12:23 UTC
### next-on-pages environment related information
Using version `@cloudflare/next-on-pages@1.6.1`
```
~/sites/edge-compute-poc$ yarn web next-on-pages --info
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open '.yarnrc.yml'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '.yarnrc.yml'
}
```

### Description

Currently `next-on-pages` assumes the `.yarnrc.yml` is always present in directory from where the script is ran. [See here](https://github.com/cloudflare/next-on-pages/blob/main/packages/next-on-pages/src/buildApplication/packageManagerUtils.ts#L43)

When having a monorepo (for example with Turborepo) we have the following structure:
```
- apps
 - web
  - {nextjs project}
- .yarnrc.yml
```

This will not work since the script is executed in `apps/web` and currently the file is 2 directories higher.
As a dirty hack, changing the patch to `../../.yarnrc.yml` makes the script run successfully.

### Reproduction

1. Create a monorepo using `npx create-turbo@latest`
2. Select `yarn` as package manager
3. Go into the created project folder
4. Run `yarn set version 3.3.1`
5. Run `yarn workspace web dlx @cloudflare/next-on-pages@1` to run the cloudflare pages build script
6. Be greeted with the following error ```⚡️ Watch mode unexpected error: Error: ENOENT: no such file or directory, open '.yarnrc.yml'```

### Pages Deployment Method

None

### Additional Information

I used `yarn patch @cloudflare/next-on-pages`, then follow the instructions in the terminal. The file you need to look for is the `dist/index.js` and then search for `".yarnrc.yml"` and change it to `"../../.yarnrc.yml"`.

After changing, "commit" the yarn patch as the terminal describes it and run `yarn install` again. You will now see the commands correctly work.

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by radzionc** [comment] 2023-09-21 08:10
Hey @1337LutZ! How did you implement the hack for changing the `.yarnrc` path? I'm having the same issue.

**Comment by 1337LutZ** [comment] 2023-09-21 08:13
> Hey @1337LutZ! How did you implement the hack for changing the `.yarnrc` path? I'm having the same issue.

I used `yarn patch @cloudflare/next-on-pages`, then follow the instructions in the terminal. The file you need to look for is the `dist/index.js` and then search for `".yarnrc.yml"` and change it.

**Comment by dario-piotrowicz** [comment] 2023-09-21 09:19
Hi @1337LutZ Thanks for the issue 🙂

And thanks for providing a quick workaround for it

This is something I'm planning to fix very soon as part of an effort to improve and simplify how we handle package managers related logic, sorry for it being a bit broken right now 🙇

**Comment by 1337LutZ** [comment] 2023-09-21 09:21
Nice, great to hear! 👏 
I was contemplating of creating a PR that would use `find-up` to search recursively for the file. However if you are making a bigger overhaul then I think it will not be needed :)

**Comment by dario-piotrowicz** [comment] 2023-09-21 09:24
I see 🙂

yeah don't worry this should get fixed soon 😄, but thanks a lot for the thought! ❤️

**Comment by dario-piotrowicz** [comment] 2023-09-25 20:55
@1337LutZ I've applied the refactoring I wanted to in #468, if you can please give the [PR's prerelease](https://github.com/cloudflare/next-on-pages/pull/468#issuecomment-1732548681) a shot and let me know if all works as intended for you 🙂

**Comment by dario-piotrowicz** [comment] 2023-09-26 15:33
@1337LutZ nice! 😃 

Thanks for confirming that it works! 🙏

By the way I merged the PR so it should be present in our latest [beta release](https://www.npmjs.com/package/@cloudflare/next-on-pages/v/0.0.0-5b4a5b7) you can use that one until we do a new proper release 🙂

**Comment by 1337LutZ** [comment] 2023-09-26 15:54
Nice, appreciate it!

**Comment by dario-piotrowicz** [comment] 2023-09-29 15:56
quickly reopening this as we needed to revert the changes I made 😓, I'll look into understanding the issue and reinstating those

**Closed** 2023-10-03 13:16 UTC
Labels: bug
