### ISSUE TITLE
how to use kv on nextjs? because kv is needed for our project 

### ISSUE THREAD

**Issue by hanumanjiblog** [cloudflare/next-on-pages#45] opened 2022-12-22 18:46 UTC
how to use kv on nextjs? because kv is needed for our project

**Comment by EvanScoboria** [comment] 2022-12-28 05:17
@hanumanjiblog I'm trying to wrap my head around the same thing. Did you get this sorted out?

**Comment by GregBrimble** [comment] 2022-12-30 17:09
Closed as duplicate of #1

**Closed by GregBrimble** 2022-12-30 17:09 UTC
