### ISSUE TITLE
[⚡ Feature]: Fail build when application uses `output: 'export'`

### ISSUE THREAD

**Issue by jmonster** [cloudflare/next-on-pages#524] opened 2023-10-31 16:18 UTC
### next-on-pages environment related information

My issue is with Cloudflare Pages CI deploy

<img width="966" alt="image" src="https://github.com/cloudflare/next-on-pages/assets/368767/80f34c40-0675-4f31-9a82-e65fd4aab20e">

### Description

Prior to today and for months prior things worked correctly.
Today only `/` of my NextJS Static App loads. Everything else 404s instead of returning either the proper file or falling back to `index.html`.

### Reproduction

<img width="711" alt="image" src="https://github.com/cloudflare/next-on-pages/assets/368767/f5a4d09c-8093-4a28-866f-fec299fb4927">

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Pages Deployment ID

https://6a737a02.dashboard-next.pages.dev

### Would you like to help?

- [X] Would you like to help fixing this bug?

**Comment by james-elicx** [comment] 2023-10-31 16:37
Hello, please can you share the next-on-pages, vercel, and next.js versions used by your latest deployment, and your last working deployment?

I would also like to ask if you could possibly try using the prerelease in https://github.com/cloudflare/next-on-pages/pull/517#issuecomment-1778062544 as this looks similar to a bug I encountered when making some changes in that PR.

If the prerelease doesn't fix the issue, would you also be able to share the build log located at (iirc) `.vercel/output/static/_worker.js/nop-build-log.json` when you build your app locally, and the build output config located at (iirc) `.vercel/output/config.json`?

**Comment by jmonster** [comment] 2023-11-01 00:37
While identifying which the last working deploy, I'm seeing that **we changed `next.config.js` to have `output: 'export'`** (as necessary for another non-cloudflare-deploys)

So with that I apologize for wasting your time! Although it would probably be better if the CloudFlare deploy would explicitly fail instead of halfway-working?

In case it's of any value, here is the result of `--info` when run locally:
```
System:
        Platform: darwin
        Arch: arm64
        Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
        CPU: (10) arm64 Apple M1 Pro
        Memory: 16 GB
        Shell: /opt/homebrew/bin/fish
Package Manager Used: pnpm (8.10.0)

Relevant Packages:
        @cloudflare/next-on-pages: 1.7.2
        vercel: N/A
        next: 13.5.4
```

**Comment by dario-piotrowicz** [comment] 2023-11-03 13:40
@jmonster I thought that `output: 'export'` would still work even when used with next-on-pages... but it sounds like it does not, we also do not test for it and it doesn't make much sense to use that with next-on-pages either... so yeah I agree that it might be a good idea to identify that and fail with an appropriate error message, I'll have a look 👍

(The tricky part being that the `output: 'export'` lives in userland and we do not check that, hopefully the vercel build output in that case gives some indication as to wether the build output is static or not 🤔)

**Comment by dario-piotrowicz** [comment] 2023-11-05 19:20
I had a quick look and there isn't really anything that clearly indicates whether the `export` output option is used.

The only thing we can check is whether edge functions have been generated or not. With `output: 'export'` none is generated, without the option usually some is usually generated but they might also not be depending on the application (but if your application does not generate and edge function then most likely you could indeed just export it as a static one).

We already check for the functions presence, but we simply log the fact that none was generated ([code](
https://github.com/cloudflare/next-on-pages/blob/bf57ec9d01b354ea6c9b9bd17c683d592d5c6ae9/packages/next-on-pages/src/buildApplication/buildApplication.ts#L112C1-L114)).

So I would propose to do the following:
 - instead of logging `No functions detected (no functions directory generated by Vercel)`, log an error saying that no function was generated (and that the app should likely get deployed as a static one) and throw an error (casing the process to exit with a non zero status code)
 - I think people might for some reason still want to use next-on-pages when no function is generated (for example if they are just starting with their app, or similar situations?), so we should also add a CLI flag allowing the build of applications without functions generated (like `--allow-static-generation` or something along those lines)
 - the above might break existing applications so it can only be implemented in the next major release of the package

> **Note**
> This is quite relevant I believe, if you have a next app which does generate edge functions and add the `output: 'export'` config to it then the functions don't get generated (but the build does succeed). This does make me think that indeed proactively failing the build on our side might be a good way to avoid user mistakes (when for example they added `output: 'export'` by mistake or with the intention or using it only on other platforms, etc...).

 
 That should be helpful right @jmonster? :slightly_smiling_face: 
 
 @james-elicx what do you think? do you like the idea?

**Comment by james-elicx** [comment] 2023-11-05 19:46
> I had a quick look and there isn't really anything that clearly indicates whether the `export` output option is used.
> 
> The only thing we can check is whether edge functions have been generated or not. With `output: 'export'` none is generated, without the option usually some is usually generated but they might also not be depending on the application (but if your application does not generate and edge function then most likely you could indeed just export it as a static one).
> 
> We already check for the functions presence, but we simply log the fact that none was generated ([code](https://github.com/cloudflare/next-on-pages/blob/bf57ec9d01b354ea6c9b9bd17c683d592d5c6ae9/packages/next-on-pages/src/buildApplication/buildApplication.ts#L112C1-L114)).
> 
> So I would propose to do the following:
> 
> * instead of logging `No functions detected (no functions directory generated by Vercel)`, log an error saying that no function was generated (and that the app should likely get deployed as a static one) and throw an error (casing the process to exit with a non zero status code)
> * I think people might for some reason still want to use next-on-pages when no function is generated (for example if they are just starting with their app, or similar situations?), so we should also add a CLI flag allowing the build of applications without functions generated (like `--allow-static-generation` or something along those lines)
> * the above might break existing applications so it can only be implemented in the next major release of the package
> 
> Note This is quite relevant I believe, if you have a next app which does generate edge functions and add the `output: 'export'` config to it then the functions don't get generated (but the build does succeed). This does make me think that indeed proactively failing the build on our side might be a good way to avoid user mistakes (when for example they added `output: 'export'` by mistake or with the intention or using it only on other platforms, etc...).
> 
> That should be helpful right @jmonster? 🙂
> 
> @james-elicx what do you think? do you like the idea?

I have to strongly disagree with that approach I'm afraid. Apps can be fully prerendered without using `output: 'export'` and there should be no assumption that an app must have an edge function to need to use next-on-pages. Static exports come with their own [limitations](https://nextjs.org/docs/pages/building-your-application/deploying/static-exports#unsupported-features) and we should not throw an error just because no edge functions exist. We can encourage people to use static exports if they have no functions, but we should make the build fail by default.

We should actually work fine with static exports, at least from my experience. I just tried doing a build while using `output: 'export'` with my blog and everything seemed to work fine. So I also think failing the build when a static export is used is not really an okay way to deal with things.

I still want to think that the infinite redirect in the pages.dev link further above was related to the infinite redirect i fixed in that base path PR (the index.html stripping for the assets fetcher). It would be nice if we could get the nop-build-log.json for OP's app's static export, or if OP would be open to trying out the beta release of next-on-pages with his failing build to see if that was the cause.

**Comment by dario-piotrowicz** [comment] 2023-11-05 20:10
> Static exports come with their own [limitations](https://nextjs.org/docs/pages/building-your-application/deploying/static-exports#unsupported-features) and we should not throw an error just because no edge functions exist.

yeah that's a valid point, I forgot about those... :sweat: 

> We can encourage people to use static exports if they have no functions, but we should not make the build fail by default, or lock the build behind a flag.

did you mean discourage?

yeah I was thinking about this too, and that we could have a flag like `--disallow-static` or something to specifically ask the process to fail when it is specified, that however seems a bit pointless at that point :thinking:

___

Anyways I don't know, it still feels like a valid idea... but I am not extremely set on it, if you disagree (and you do make valid points as to why) I don't mind dropping it, I think it would be nice to help people finding potential issues/problems but of course if it's going to cause more problems/annoyance then it is worth then I agree that it's not really worth it :thinking:

**Comment by dario-piotrowicz** [comment] 2023-11-05 20:13
Anyways as I said it doesn't look like the vercel output is any help in checking if `output: 'export'` is being used, and if we don't go with disallowing apps with no functions then I guess we're out of options for this one and we can only leave it as is...

There's still the option to read the `next.config.js` file, which we've been thinking on and of for a while.... :thinking:

**Comment by james-elicx** [comment] 2023-11-05 20:18
> > We can encourage people to use static exports if they have no functions, but we should not make the build fail by default, or lock the build behind a flag.
> 
> did you mean discourage?
>
> yeah I was thinking about this too, and that we could have a flag like `--disallow-static` or something to specifically ask the process to fail in that case when it is specified, that however seems a bit pointless at that point 🤔

no, i meant to encourage people to use static exports without/instead of next-on-pages. static exports should work fine with next-on-pages, but we can log a warning recommending they try it without if there are no functions, but we should never error or fail because there are no edge functions. i would consider failing a build because there are no edge functions to be a bug.

**Comment by dario-piotrowicz** [comment] 2023-11-20 23:45
@jmonster Given the conversation above I assume that it's unlikely that we're going to actually fail the build when the user is using `output: 'export'`, if it helps we can add a warning, please let me know if that would help

If you want you could share with us more details so that we can try to understand why your app is only half working, especially if your other non-cloudflare-deploys work differently (if they all half-work then I would assume this to be a user error and not a next-on-pages one).

Otherwise I think we can close this issue

**Comment by dario-piotrowicz** [comment] 2023-12-19 11:36
Closing due to the lack of response

@jmonster I hope you don't mind, if you circle back to this please feel free to reopen this issue or create a new one

**Closed by dario-piotrowicz** 2023-12-19 11:36 UTC
Labels: bug, question
