### ISSUE TITLE
[🐛 Bug]: Error: Failed to publish your Function. Got error: Your Functions script is over the 1 MiB size limit (workers.api.error.script_too_large)

### ISSUE THREAD

**Issue by PPHelios** [cloudflare/next-on-pages#523] opened 2023-10-30 13:10 UTC
### next-on-pages environment related information

PS C:\Projects\bw-cloudflare> npx @cloudflare/next-on-pages --info
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn bash ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn bash',
  path: 'bash',
  spawnargs: [ '--noprofile', '--norc' ]
}

Node.js v18.15.0

### Description

Hi,
I'm new to cloudflare workers and I’m trying to deploy a Next js app but I’m getting an error :

`Error: Failed to publish your Function. Got error: Your Functions script is over the 1 MiB size limit (workers.api.error.script_too_large)`

I installed  cloudflare/next-on-pages , connected  pages to my GitHub repo and configured Build configurations.

kindly find attached the output log.

[bw-cloudflare.c3565838-8d5b-4938-96e1-0c1cf76bee98.log](https://github.com/cloudflare/next-on-pages/files/13205394/bw-cloudflare.c3565838-8d5b-4938-96e1-0c1cf76bee98.log)

what is ccausing tis error? and how to solve it?

The build output file sizes is :

14:39:11.960 | ▲  Route (app)                                         Size     First Load JS
-- | --
14:39:11.960 | ▲  ┌ ℇ /                                               0 B                0 B
14:39:11.960 | ▲  ├ ○ /_not-found                                     889 B          82.5 kB
14:39:11.960 | ▲  ├ ℇ /[lng]                                          3.83 kB         373 kB
14:39:11.961 | ▲  ├ ● /[lng]/about-us                                 173 B           232 kB
14:39:11.961 | ▲  ├   ├ /ar/about-us
14:39:11.961 | ▲  ├   └ /en/about-us
14:39:11.961 | ▲  ├ ℇ /[lng]/add-property/[[...slug]]                 5.92 kB         451 kB
14:39:11.961 | ▲  ├ ℇ /[lng]/admin-panel/add/[target]                 4.52 kB         383 kB
14:39:11.961 | ▲  ├ ℇ /[lng]/admin-panel/agencies                     3.74 kB         236 kB
14:39:11.962 | ▲  ├ ℇ /[lng]/admin-panel/analytics                    45 kB           399 kB
14:39:11.962 | ▲  ├ ℇ /[lng]/admin-panel/edit-agent/[...id]           4.96 kB         383 kB
14:39:11.962 | ▲  ├ ℇ /[lng]/admin-panel/listed-properties            8.87 kB         263 kB
14:39:11.962 | ▲  ├ ℇ /[lng]/admin-panel/logs                         5.32 kB         359 kB
14:39:11.963 | ▲  ├ ℇ /[lng]/admin-panel/review-list/[...edited]      5.93 kB         360 kB
14:39:11.963 | ▲  ├ ℇ /[lng]/admin-panel/review-property/[[...slug]]  459 B           258 kB
14:39:11.964 | ▲  ├ ℇ /[lng]/admin-panel/users                        5.76 kB         360 kB
14:39:11.964 | ▲  ├ ● /[lng]/chat                                     5.31 kB         242 kB
14:39:11.964 | ▲  ├   ├ /ar/chat
14:39:11.964 | ▲  ├   └ /en/chat
14:39:11.964 | ▲  ├ ● /[lng]/contact-us                               3.92 kB         372 kB
14:39:11.964 | ▲  ├   ├ /ar/contact-us
14:39:11.965 | ▲  ├   └ /en/contact-us
14:39:11.965 | ▲  ├ ● /[lng]/edit-profile                             5.21 kB         383 kB
14:39:11.965 | ▲  ├   ├ /ar/edit-profile
14:39:11.965 | ▲  ├   └ /en/edit-profile
14:39:11.965 | ▲  ├ ℇ /[lng]/edit-property/[[...slug]]                5.98 kB         451 kB
14:39:11.965 | ▲  ├ ● /[lng]/faq                                      2.88 kB         252 kB
14:39:11.965 | ▲  ├   ├ /ar/faq
14:39:11.966 | ▲  ├   └ /en/faq
14:39:11.966 | ▲  ├ ● /[lng]/favorites                                4.53 kB         366 kB
14:39:11.966 | ▲  ├   ├ /ar/favorites
14:39:11.966 | ▲  ├   └ /en/favorites
14:39:11.966 | ▲  ├ ● /[lng]/login                                    3.59 kB         393 kB
14:39:11.966 | ▲  ├   ├ /ar/login
14:39:11.966 | ▲  ├   └ /en/login
14:39:11.966 | ▲  ├ ● /[lng]/privacy                                  173 B           232 kB
14:39:11.967 | ▲  ├   ├ /ar/privacy
14:39:11.967 | ▲  ├   └ /en/privacy
14:39:11.967 | ▲  ├ ℇ /[lng]/property-details/[[...slug]]             219 B           258 kB
14:39:11.967 | ▲  ├ ● /[lng]/reset-password                           4.2 kB          386 kB
14:39:11.968 | ▲  ├   ├ /ar/reset-password
14:39:11.968 | ▲  ├   └ /en/reset-password
14:39:11.968 | ▲  ├ ● /[lng]/roles-description                        173 B           232 kB
14:39:11.968 | ▲  ├   ├ /ar/roles-description
14:39:11.968 | ▲  ├   └ /en/roles-description
14:39:11.968 | ▲  ├ ℇ /[lng]/search/[[...slug]]                       4.92 kB         395 kB
14:39:11.968 | ▲  ├ ● /[lng]/signup                                   5.79 kB         395 kB
14:39:11.969 | ▲  ├   ├ /ar/signup
14:39:11.969 | ▲  ├   └ /en/signup
14:39:11.969 | ▲  ├ ● /[lng]/terms-of-service                         173 B           232 kB
14:39:11.969 | ▲  ├   ├ /ar/terms-of-service
14:39:11.969 | ▲  ├   └ /en/terms-of-service
14:39:11.969 | ▲  ├ ○ /robots.txt                                     0 B                0 B
14:39:11.969 | ▲  └ ○ /sitemap.xml                                    0 B                0 B
14:39:11.969 | ▲  + First Load JS shared by all                       81.6 kB
14:39:11.970 | ▲  ├ chunks/5158-8ad0e7e2647249f2.js                 27.6 kB
14:39:11.970 | ▲  ├ chunks/fd9d1056-26763e011dd3506d.js             50.9 kB
14:39:11.970 | ▲  ├ chunks/main-app-74f06970312ecd1b.js             260 B
14:39:11.970 | ▲  └ chunks/webpack-c771f841da7a57b7.js              2.78 kB
`

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Pages Deployment ID

c3565838-8d5b-4938-96e1-0c1cf76bee98

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment] 2023-11-20 23:58
Hi @PPHelios, thanks for trying next-on-pages and for opening this issue 🙂 

Given the log you shared I think that unfortunately your application is simply too large to fit in the [Cloudflare Workers free tier](https://developers.cloudflare.com/workers/platform/limits/#worker-size), the only thing I can suggest would be for you to try the paid tear ($5/mo). That would increase the limit to 10 MB which should be quite enough for large applications.

**Comment by dario-piotrowicz** [comment] 2023-12-01 15:55
I'm closing the issue since as I mentioned above I think that this is most likely not a bug with next-on-pages but a limitation of the Cloudflare platform.

@PPHelios If you disagree (or have suggestions on how we could document this better) please let me know and feel free to reopen this issue 🙂 🙏

**Closed by dario-piotrowicz** 2023-12-01 15:55 UTC
Labels: bug
