### ISSUE TITLE
[🐛 Bug]: Could not resolve "/wasm/wasm..." when building a Next.js 13 application making use of @cloudflare/pages-plugin-vercel-og

### ISSUE THREAD

**Issue by leonlarsson** [cloudflare/next-on-pages#165] opened 2023-04-10 20:38 UTC
### Cli version

0.7.0

### Next.js related information

    Operating System:       Platform: win32       Arch: x64       Version: Windows 10 Home     Binaries:       Node: 16.13.1       npm: N/A       Yarn: N/A       pnpm: N/A     Relevant packages:       next: 13.3.1-canary.4       eslint-config-next: N/A       react: 18.2.0       react-dom: 18.2.0

### Vercel version

28.18.4

### Description

I'm currently trying out https://developers.cloudflare.com/pages/platform/functions/plugins/vercel-og/#generate-arbitrary-images together with Next.js 13, but I'm getting errors in the build deployment to Pages.

Using this: https://nextjs.org/blog/next-13-3#dynamic-open-graph-image-generation, but replaced import `{ ImageResponse } from "next/server"` with `import { ImageResponse } from "@cloudflare/pages-plugin-vercel-og/api"` I get the following errors (full build log in "Additional Information"):
```
2023-04-10T19:36:19.642134Z	✘ [ERROR] Could not resolve "/wasm/wasm_a7e702bc5ba9227243abda7977c8096f59478d3f.wasm"
2023-04-10T19:36:19.642428Z	
2023-04-10T19:36:19.642575Z	    ../../../tmp/6jxw73kufh8/image/[name].func.js:1:62:
2023-04-10T19:36:19.642711Z	      1 │ ... = require("/wasm/wasm_a7e702bc5ba9227243abda7977c8096f59478d3f....
2023-04-10T19:36:19.642827Z	        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-04-10T19:36:19.642934Z	
2023-04-10T19:36:19.643055Z	✘ [ERROR] Could not resolve "/wasm/wasm_ea9ee43a5ee9b2e1cd270fa43980822c06dc5bf2.wasm"
2023-04-10T19:36:19.643167Z	
2023-04-10T19:36:19.643271Z	    ../../../tmp/6jxw73kufh8/image/[name].func.js:2:62:
2023-04-10T19:36:19.643384Z	      2 │ ... = require("/wasm/wasm_ea9ee43a5ee9b2e1cd270fa43980822c06dc5bf2....
2023-04-10T19:36:19.643489Z	        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-04-10T19:36:19.643592Z	
2023-04-10T19:36:19.699811Z	✘ [ERROR] Could not resolve "/wasm/wasm_a7e702bc5ba9227243abda7977c8096f59478d3f.wasm"
2023-04-10T19:36:19.700086Z	
2023-04-10T19:36:19.700252Z	    ../../../tmp/6jxw73kufh8/image/[name]/opengraph-image.func.js:1:62:
2023-04-10T19:36:19.700376Z	      1 │ ... = require("/wasm/wasm_a7e702bc5ba9227243abda7977c8096f59478d3f....
2023-04-10T19:36:19.700523Z	        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-04-10T19:36:19.700647Z	
2023-04-10T19:36:19.700768Z	✘ [ERROR] Could not resolve "/wasm/wasm_ea9ee43a5ee9b2e1cd270fa43980822c06dc5bf2.wasm"
2023-04-10T19:36:19.700883Z	
2023-04-10T19:36:19.700998Z	    ../../../tmp/6jxw73kufh8/image/[name]/opengraph-image.func.js:2:62:
2023-04-10T19:36:19.701108Z	      2 │ ... = require("/wasm/wasm_ea9ee43a5ee9b2e1cd270fa43980822c06dc5bf2....
2023-04-10T19:36:19.70122Z	        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-04-10T19:36:19.701324Z	
2023-04-10T19:36:19.701431Z	✘ [ERROR] Could not resolve "/wasm/wasm_ef4866ecae192fd87727067cf2c0c0cf9fb8b020.wasm"
2023-04-10T19:36:19.701537Z	
2023-04-10T19:36:19.701661Z	    ../../../tmp/6jxw73kufh8/image/[name]/opengraph-image.func.js:3:62:
2023-04-10T19:36:19.701772Z	      3 │ ... = require("/wasm/wasm_ef4866ecae192fd87727067cf2c0c0cf9fb8b020....
2023-04-10T19:36:19.701936Z	        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
``` 

### Reproduction

The repo that I'm deploying on Cloudflare Pages is the following: https://github.com/leonlarsson/bfstats-web/tree/dev
The root of the issue is in `/app/image/opengraph-image.tsx`

Note: I use `next@13.3.1-canary.4` because it fixes a breaking bug.

**Cloudflare Pages build settings**
```
Build command: npx @cloudflare/next-on-pages --experimental-minify
Build output directory: /.vercel/output/static
```
**Cloudflare Pages environment variables**
```
NODE_VERSION: 16
```
**Cloudflare Pages functions compatibility**
```
Compatibility date: 2023-03-14
Compatibility flags: nodejs_compat
```

### Additional Information

These are the deploy logs including errors from deploying the above mentioned repo: [bfstats-web.ea9a9ade-537c-4a22-9633-d7d023ae8aa3.log](https://github.com/cloudflare/next-on-pages/files/11193720/bfstats-web.ea9a9ade-537c-4a22-9633-d7d023ae8aa3.log)

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment] 2023-04-11 09:46
Hi @leonlarsson, thanks for the issue 🙂 

And thank you a lot for the reproduction, I bet that's going to be super useful 😄👍  

Anyways I'm closing this as I think it's a duplicate of https://github.com/cloudflare/next-on-pages/issues/39, so to keep things simple let's just keep all the conversation there.

(If you think this issue is not a duplicate please let me know and we can reopen it)

**Closed by dario-piotrowicz** 2023-04-11 09:46 UTC
Labels: bug

**Comment by dario-piotrowicz** [comment] 2023-04-11 12:02
Note: to reproduce the issue in your repository I believe we need to use this commit: https://github.com/leonlarsson/bfstats-web/commit/f73e941467cd1d3b7190d8e4b3cba31d141fcd69 (since after that you're removing the image opengraph-image page)

**Comment by dario-piotrowicz** [comment] 2023-04-11 12:14
@leonlarsson does your app (on `f73e941`) work if you just use next? (`next dev`)? (because it doesn't seem to work for me)

**Comment by leonlarsson** [comment] 2023-04-11 12:40
> @leonlarsson does your app (on `f73e941`) work if you just use next? (`next dev`)? (because it doesn't seem to work for me)

I've been using the dev branch more recently to test it out to leave main working.
[I just updated the dev branch](https://github.com/leonlarsson/bfstats-web/commit/d901de84a50f9ea81f2e9ff7b299bd9108954b48) to better test it out. And the current dev branch works as expected when running `npx next dev`, but I get the same error when deployed to CF Pages. Going to /image now properly renders an image.

I also deployed the dev branch to Vercel to test, and that also seems to work. Even the opengraph-image works: https://bfstats-ajqmz5x86-leonlarsson.vercel.app/image

**Comment by dario-piotrowicz** [comment] 2023-04-11 15:01
Ok not a problem, the wasm issue anyways is definitely a thing, so we'll look into it 🙂👍

**Comment by leonlarsson** [comment] 2023-05-01 14:36
Have there been any findings?

**Comment by dario-piotrowicz** [comment] 2023-05-01 17:38
@leonlarsson yeah please have a look at my comment: https://github.com/cloudflare/next-on-pages/issues/39#issuecomment-1522312812

Basically two things need to be done, one here and one in the pages-plugins repo, I will do the fix here soon (I am just waiting for https://github.com/cloudflare/next-on-pages/pull/191 to get merged first as that changes the solution for the `wasm` importing), the pages-plugins I am not too sure, maybe I'll have a crack at it as well or maybe @GregBrimble will, we shall see :slightly_smiling_face:
