### ISSUE TITLE
Build failed with MUI v5

### ISSUE THREAD

**Issue by itsminh99** [cloudflare/next-on-pages#15] opened 2022-10-29 09:12 UTC
I setup MUI V5 with _app.tsx and _document in example link: https://github.com/mui/material-ui/tree/master/examples/nextjs-with-typescript/pages.

`
info  - Collecting page data...
--
16:02:47.297 | ▲
16:02:48.060 | ▲ evalmachine.<anonymous>:1341
16:02:48.060 | ▲     var ssrStyles = document.querySelectorAll("style[data-emotion]:not([data-s])"); // get SSRed styles out of the way of React's hydration
16:02:48.089 | ▲                     ^
16:02:48.089 | ▲
16:02:48.090 | ▲ ReferenceError: document is not defined
16:02:48.090 | ▲     at createCache (evalmachine.<anonymous>:1341:21)
16:02:48.090 | ▲     at createEmotionCache (evalmachine.<anonymous>:109:56)
16:02:48.090 | ▲     at Object.8139 (evalmachine.<anonymous>:668:71)
16:02:48.090 | ▲     at __webpack_require__ (evalmachine.<anonymous>:25:42)
16:02:48.090 | ▲     at Object.5270 (evalmachine.<anonymous>:30:20)
16:02:48.090 | ▲     at __webpack_require__ (evalmachine.<anonymous>:25:42)
16:02:48.091 | ▲     at __webpack_exec__ (evalmachine.<anonymous>:355:48)
16:02:48.091 | ▲     at evalmachine.<anonymous>:356:56
16:02:48.091 | ▲     at Function.__webpack_require__.O (evalmachine.<anonymous>:63:23)
16:02:48.091 | ▲     at evalmachine.<anonymous>:357:56
16:02:48.091 | ▲
16:02:48.091 | ▲
16:02:48.091 | ▲ > Build error occurred
16:02:48.092 | ▲
16:02:48.092 | ▲ Error: Failed to collect page data for /abc
16:02:48.092 | ▲     at /opt/buildhome/repo/node_modules/next/dist/build/utils.js:916:15
16:02:48.092 | ▲     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
16:02:48.092 | ▲   type: 'Error'
16:02:48.092 | ▲ }
16:02:48.092 | ▲
`
`

info  - Collecting page data...
--
15:56:00.281 | ▲
15:56:00.924 | ▲ evalmachine.<anonymous>:3525
15:56:00.924 | ▲ var asyncWrite =  true && ['v0.10', 'v0.9.'].indexOf(process.version.slice(0, 5)) > -1 ? setImmediate : pna.nextTick;
15:56:00.924 | ▲                                                                      ^
15:56:00.925 | ▲
15:56:00.925 | ▲ TypeError: Cannot read property 'slice' of undefined
15:56:00.925 | ▲     at Object.1690 (evalmachine.<anonymous>:3525:70)
15:56:00.925 | ▲     at __webpack_require__ (evalmachine.<anonymous>:25:42)
15:56:00.925 | ▲     at Object.1090 (evalmachine.<anonymous>:4340:20)
15:56:00.925 | ▲     at __webpack_require__ (evalmachine.<anonymous>:25:42)
15:56:00.925 | ▲     at Object.4422 (evalmachine.<anonymous>:1948:14)
15:56:00.925 | ▲     at __webpack_require__ (evalmachine.<anonymous>:25:42)
15:56:00.926 | ▲     at Object.2313 (evalmachine.<anonymous>:7117:16)
15:56:00.926 | ▲     at __webpack_require__ (evalmachine.<anonymous>:25:42)
15:56:00.926 | ▲     at Object.888 (evalmachine.<anonymous>:1451:67)
15:56:00.926 | ▲     at __webpack_require__ (evalmachine.<anonymous>:25:42)
15:56:00.926 | ▲
15:56:00.929 | ▲
15:56:00.929 | ▲ > Build error occurred
15:56:00.929 | ▲ Error: Failed to collect page data for /
15:56:00.929 | ▲     at /opt/buildhome/repo/node_modules/next/dist/build/utils.js:916:15
15:56:00.929 | ▲     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
15:56:00.929 | ▲   type: 'Error'
15:56:00.929 | ▲ }
15:56:00.930 | ▲
15:56:00.990 | ▲ npm ERR! code ELIFECYCLE
15:56:00.991 | ▲

`

**Comment by judemanutd** [comment] 2022-11-13 09:40
+1

**Comment by dario-piotrowicz** [comment] 2023-04-05 11:36
Hi @itsminh99 sorry for the late reply to this issue 🙇 

It seems like your link is no longer valid, I have tried with this instead: https://github.com/mui/material-ui/tree/master/examples/material-next-ts (since I think is just the same example but renamed)

I had to tweak some stuff since it seems not to build (even their stackblitz fails build) but then it seems to work nicely with next-on-pages as you can see from the [deployed app](https://material-ui-example-nextjs-ts-cf-pages.pages.dev/) (and this is [my code](https://github.com/dario-piotrowicz/material-ui-example-nextjs-ts-cf-pages))

But anyways this seems to build with just SSG and there isn't any SSR, I guess they either changes their example or you've added some SSR code?

Could you please check and let me know if the build error you presented is still an issue? and if it is it would be awesome if you could provide the reproduction steps 🙏

**Comment by dodrian** [comment] 2023-04-10 14:12
Also note that your build will fail at the collecting page data step if you have a `_document.tsx` file (including @dario-piotrowicz's example app) when you set the config runtime to 'experimental-edge' due to [this upstream issue](https://github.com/vercel/next.js/issues/40440).

**Comment by dario-piotrowicz** [comment] 2023-05-02 16:28
We probably don't have enough details to investigate this issue, it might actually be already solved

In order to keep only relevant and actionable issues I am closing this one since I didn't received a reply from the author in about a month

@itsminh99 (or @judemanutd since you one-upped the issue) if you encounter this issue again please let me know here or feel free to open a new issue 🙂 

(PS: sorry for closing the issue I hope you don't mind 🙏, I just don't want risking to keep it open/unactionable around indefinitely)

**Closed by dario-piotrowicz** 2023-05-02 16:28 UTC
Labels: question, build error
