### ISSUE TITLE
Unable to locate .env variables defined in the server side

### ISSUE THREAD

**Issue by Shadid12** [cloudflare/next-on-pages#59] opened 2023-01-25 12:12 UTC
## Unable to access the defined environment variables in the Next.js `getServerSideProps()` function.

To reproduce: 
1. Create some new environment variables by going to **Pages** > **your Pages project** > **Settings** > **Environment variables**
2. <img width="1397" alt="Screen Shot 2023-01-25 at 7 08 34 AM" src="https://user-images.githubusercontent.com/10352180/214559940-684e7a33-07d2-46dd-96de-c5b97efd1a2e.png">
3. Add the following code in your `index.js` file

```jsx

export const config = {
  runtime: 'experimental-edge',
}


export async function getServerSideProps() {
  const fauna_secret = process.env.FAUNA_SECRET;
  const node_env = process.env.NODE_VERSION;
  const products = await getProducts();
  return {
    props: {
      products,
      fauna_secret,
      node_env
    },
  }
}


export default function Home({ products, fauna_secret, node_env }) {
  console.log(products);
  console.log('===>', fauna_secret); // will be undefined
  console.log('===>', node_env);  // will be undefined
  return (
    <div className={styles.container}>
      <h1>Products</h1>
      ...
      </ul>
    </div>
  )
}
```
4. Deploy 
5. Notice environment variables are going to be undefined

**Comment by GregBrimble** [comment] 2023-01-25 12:29
Closed as duplicate of #1

**Closed by GregBrimble** 2023-01-25 12:29 UTC
