### ISSUE TITLE
[🐛 Bug]: Inconsistent behavior for API-routes and `trailingSlash`

### ISSUE THREAD

**Issue by gabrielf** [cloudflare/next-on-pages#665] opened 2024-02-15 11:13 UTC
### next-on-pages environment related information

npx @cloudflare/next-on-pages --info

System:
	Platform: darwin
	Arch: arm64
	Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:31:00 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6020
	CPU: (12) arm64 Apple M2 Pro
	Memory: 16 GB
	Shell: /bin/zsh
Package Manager Used: npm (9.8.1)

Relevant Packages:
	@cloudflare/next-on-pages: 1.9.0
	vercel: N/A
	next: 14.1.0

### Description

API routes in a Next.js app using `trailingSlash: true` behaves inconsistently in regards to trailing slashes when run using `next-on-pages` + wrangler compared to `npm run dev`.

The actual behavior depends on whether i18n is activate or not and whether a middleware is present or not.

In the below tests I've used Next.js 14.1.0 and `trailingSlash: on`. I've tested an API route in both the pages router (`/api/hello-pages`) and the app router (`/api/hello-app`).

The expected behavior is to get a 308 when requesting `/api/hello-(pages|app)` (no trailing slash) and a 200 when requesting `/api/hello-(pages|app)/` (with trailing slash). `npm run dev` does this in all cases.

These are the results when performing the same tests using `next-on-pages`+`wrangler`:

|                        | i18n off                      | i18n on |
|------------------------|-------------------------------|---------|
| <strong>middleware not present</strong> | <ul><li>no slash: 308</li><li>slash: 200</li></ul> |  <ul><li>no slash: 308</li><li>slash: <em>404</em>‼️</li></ul>  |
| <strong>middleware present</strong>     | <ul><li>no slash: <em>200</em>❗️</li><li>slash: 200</li></ul> | <ul><li>no slash: <em>200</em>❗️</li><li>slash: <em>404</em>‼️</li></ul> |

### Reproduction

https://github.com/gabrielf/wrangler-api-route-trailing-slash

The above repo contains a minimal Next.js app and the script `./test.sh` that when run will start the app, run some tests, quit the app and generates output showing the test results.

### Pages Deployment Method

None

### Additional Information

Getting a 200 for an API route when it should be a 308 is OK I guess but it would be nice if the behavior was exactly the same as running with `npm run dev` for consistency.

### Would you like to help?

- [X] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment] 2024-03-05 23:51
@gabrielf thanks so very much for the issue, and I can't thank you enough for the reproduction! very high quality and extremely helpful! Thanks so much! ❤️ ❤️ ❤️ 

(PS: and so sorry for the late reply 🙇 )
___

I've opened #692 which I think fixes the `404` cases:
![Screenshot 2024-03-05 at 23 43 42](https://github.com/cloudflare/next-on-pages/assets/61631103/a89b6ac5-20bb-4d30-9770-c13878d384c4)

If you want please feel free to have a look, try the prerelease and let me know if you can confirm that the change fixes all the `404`s you've seen 🙂 

If that's the case I guess the `200`s not being `308`s is the only remaining issue right?

___

> [!NOTE]
> I know you ticked the `Would you like to help fixing this bug?` but this was one of those issues in which finding what might be going wrong was already practically solving the thing (since it is a one line change), so, sorry about doing it myself, but thanks a lot for offering to help anyways 🙂 🙏 
>
> I'll look at the `308`s in the next few days as soon as I have some time 🙂, but if you want to have a stub at it please let me know and I can leave it to you this time 🙂 (and can give you some guidance on how to investigate the issue)

**Comment by dario-piotrowicz** [comment] 2024-03-07 16:48
(reopening the issue as it was closed by mistake)

**Comment by dario-piotrowicz** [comment] 2024-03-10 15:05
I've opened this separate issue for the `308` bug: #696 and have already a fix for it almost ready 🙂

(I wanted to have a separate focused issue on it so that I can reference it in the e2e tests)

Once #696 is closed this issue should be closed as well 🙂 (after we confirm that it's all working as intended).

**Comment by dario-piotrowicz** [comment] 2024-03-13 12:03
@gabrielf it should be all good now 🙂 

If you try the latest `beta` release you should now see the expected results:

![Screenshot 2024-03-13 at 11 59 32](https://github.com/cloudflare/next-on-pages/assets/61631103/d742979d-5e94-47c0-b25f-bcd9b99d7a2d)

![Screenshot 2024-03-13 at 12 00 52](https://github.com/cloudflare/next-on-pages/assets/61631103/6ce345b2-5291-4c6c-a57b-3749236327b2)


I'm closing the issue as I think it is solved, but if you disagree please do feel free to reopen it 🙂

**Closed by dario-piotrowicz** 2024-03-13 12:03 UTC
Labels: bug

**Comment by gabrielf** [comment] 2024-03-18 10:13
@dario-piotrowicz sorry for not getting back to you earlier, must get my Github notifications in order! When I try the beta I get the expected results below, wonderful! I tried to send you an email on the 28th of February. Could you have a look?

<img width="289" alt="image" src="https://github.com/cloudflare/next-on-pages/assets/137649/153b947b-f415-4972-a425-818a0a425bb5">
