### ISSUE TITLE
[🐛 Bug]: Could not deploy under git submodule

### ISSUE THREAD

**Issue by vioao** [cloudflare/next-on-pages#677] opened 2024-02-23 07:56 UTC
### next-on-pages environment related information

`"@cloudflare/next-on-pages": "^1.8.5" `

### Description

When running the `npm run pages:deploy` under a git submodule
>  "pages:deploy": "npm run pages:build && wrangler pages deploy .vercel/output/static",
Will get the error
> ▲  Vercel CLI 33.3.0
> ▲  Error: ENOTDIR: not a directory, lstat '/Users/vioao/Documents/side-project/projects/cf-magazines/.git/config'
> ⚡️ The Vercel build (`npx vercel build`) command failed. For more details see the Vercel logs above.
> ⚡️ If you need help solving the issue, refer to the Vercel or Next.js documentation or their repositories.

### Pages Deployment Method

None

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by vioao** [comment] 2024-02-23 09:46
might be related with this issue.
https://github.com/vercel/vercel/issues/10104

**Comment by dario-piotrowicz** [comment] 2024-03-05 10:30
Hi @vioao, thank you for the issue 🙂 

`@cloudflare/next-on-pages` under the hood calls the vercel CLI, so as you mentioned this issue seems to be caused by https://github.com/vercel/vercel/issues/10104 and as soon as that is resolved by Vercel the problem should disappear here as well.

We don't keep track of such issues (since anyways there is nothing actionable to do for us in this codebase).

So I am closing this issue, I hope that's fine by you, please feel free to reopen it if you disagree 🙂

**Closed by dario-piotrowicz** 2024-03-05 10:30 UTC
Labels: bug

**Comment by vioao** [comment] 2024-03-28 02:53
Sure. NP. Thanks
