### ISSUE TITLE
[🐛 Bug]: Export Path for ./bin Missing in package.json

### ISSUE THREAD

**Issue by khalil-omer** [cloudflare/next-on-pages#543] opened 2023-11-14 17:14 UTC
### next-on-pages environment related information

```
System:
	Platform: darwin
	Arch: arm64
	Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
	CPU: (10) arm64 Apple M1 Pro
	Memory: 32 GB
	Shell: /bin/zsh
Package Manager Used: npm (8.19.2)

Relevant Packages:
	@cloudflare/next-on-pages: 1.7.3
	vercel: N/A
	next: N/A
```

### Description

_I'm filing this as a bug, but maybe you feel it is a feature request. it's a one line fix._ 

When using `@cloudflare/next-on-pages` with `@naxodev/nx-cloudflare`, an error occurs due to a missing export path in the `package.json` of `@cloudflare/next-on-pages`. The error is related to the package subpath './bin' not being defined in the "exports" field of `package.json`.

### Error Message
The specific error message encountered is:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './bin' is not defined by "exports" in /.../node_modules/@cloudflare/next-on-pages/package.json
```

### Expected Behavior
The package should export the `./bin` subpath to allow other tools or packages to correctly access the binaries required for operations.

### Actual Behavior
The `bin` directory is not exported in the `package.json`, causing the above error when trying to access `./bin/index.js`.

### Temporary Solution
A temporary solution that resolved the issue was to modify the `package.json` of `@cloudflare/next-on-pages` to include the `./bin` subpath in the `exports` field as follows:

```json
"exports": {
  "./__experimental__next-dev": "./dist/next-dev/index.cjs",
  "./bin": "./bin/index.js"
}
```

### Suggested Fix
I suggest that the `package.json` of `@cloudflare/next-on-pages` be updated to officially include the `./bin` subpath in the `exports` field. This would allow other packages to have peer dependencies on `next-on-pages`.

### Reproduction

1. Set up a project with `@naxodev/nx-cloudflare` (or manually try to reference `.bin/index.js` 
2. Run a build command programmatically 
4. Observe the error related to the package subpath './bin'.

### Pages Deployment Method

None

### Would you like to help?

- [x] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment] 2023-11-15 17:28
Hi @khalil-omer, thanks for the issue 🙂 

The next-on-pages package is not supposed to be used programmatically but as a CLI tool, so that's why bin is not being exported and I would prefer it if we could not export the binary (not for any specific reason but just because it feels semantically wrong to me 😅)

It seems that the issue is that `nx-cloudflare` tries to get the path of next-on-pages in the following way:
https://github.com/naxodev/oss/blob/783726bd1c0a13b5876a57c8274b17745da69b0b/packages/plugins/nx-cloudflare/src/executors/next-build/build.impl.ts#L147

Could you instead try to open an issue there and/or contribute there and see if maybe we can replace the path detection with the following (that relies on the `next-dev` submodule to discern the next-on-pages location):
```diff
-      require.resolve('@cloudflare/next-on-pages/bin'),
+      path.resolve(require.resolve('@cloudflare/next-on-pages/next-dev'), '../../..'),
```
? 🙏 

What do you think?

If the above is not ok (for example the author refuses the change, etc...) I think we can add the bin entry in the exports here as you mentioned, but I'd personally prefer it if we could avoid that 🙂 (again, as a personal preference)

**Comment by dario-piotrowicz** [comment] 2023-11-20 23:35
@khalil-omer I'm closing this issue as I believe it has been fixed in the `nx-cloudflare` package 🙂 

I hope it's fine, if you think that the issue should not have been closed and/or that there is still something to do here please feel free to reopen it 🙂

**Closed by dario-piotrowicz** 2023-11-20 23:35 UTC
Labels: bug
